#!/usr/bin/env python3
"""Build docs/index.html: a self-contained stlite (Streamlit-on-Pyodide) build of calgen.

Run this after changing calgen.py, ical_writer.py, or special_dates.csv, then
commit docs/index.html so GitHub Pages serves the updated app.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
STLITE_VERSION = "0.90.7"
ENTRYPOINT = "calgen.py"
SOURCE_FILES = ["calgen.py", "ical_writer.py", "special_dates.csv"]

REQUIREMENTS = [
    "calendar-view>=2.4.8",
    "icalendar>=6.1.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "recurring-ical-events>=3.3.4",
    "setuptools>=75.6.0",
    "streamlit>=1.41.1",
    "tabulate>=0.9.0",
]


def to_js_template_literal(text: str) -> str:
    """Escape text for embedding inside a JS backtick template literal."""
    text = text.replace("\\", "\\\\")
    text = text.replace("`", "\\`")
    text = text.replace("${", "\\${")
    return text


def build_files_entry():
    parts = []
    for name in SOURCE_FILES:
        content = (ROOT / name).read_text()
        escaped = to_js_template_literal(content)
        parts.append(f'"{name}": `{escaped}`')
    return ",\n".join(parts)


def main():
    requirements_json = ", ".join(f'"{r}"' for r in REQUIREMENTS)
    files_entry = build_files_entry()

    html = f"""<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Workday Schedule Converter</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@stlite/browser@{STLITE_VERSION}/build/stlite.css"
    />
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
import {{ mount }} from "https://cdn.jsdelivr.net/npm/@stlite/browser@{STLITE_VERSION}/build/stlite.js"
mount(
  {{
    requirements: [{requirements_json}],
    entrypoint: "{ENTRYPOINT}",
    files: {{
{files_entry}
    }},
  }},
  document.getElementById("root")
)
    </script>
  </body>
  <!-- Generated by build_stlite.py from calgen.py, ical_writer.py, special_dates.csv. Do not edit directly. -->
</html>
"""

    out_path = ROOT / "docs" / "index.html"
    out_path.parent.mkdir(exist_ok=True)
    out_path.write_text(html)
    print(f"Wrote {out_path} ({len(html)} bytes)")


if __name__ == "__main__":
    main()
